Repository openshift-knative/hack, pull requests merged in 2024-01, with the labels that each got.

#97 increase timeout to 5h from the default 4h for mesh jobs
  config/serverless-operator.yaml
  pkg/prowgen/prowgen_config.go
  pkg/prowgen/prowgen_tests.go
Labels: lgtm, approved

#99 Run serverless-operator on OCP 4.14
  config/serverless-operator.yaml
Labels: lgtm, approved

#100 Adjust test suite to cluster size
  config/serverless-operator.yaml
Labels: lgtm, approved

#103 Use go.mod to get Go version in actions
  .github/workflows/go-unit-tests.yaml
  .github/workflows/multiarch-build.yaml
  .github/workflows/release-generate-ci.yaml
  .github/workflows/run-command-repository.yaml
Labels: lgtm, approved

#106 Generate onDemand jobs for next candidate release
  pkg/prowgen/prowgen_config.go
  pkg/prowgen/prowgen_tests.go
Labels: lgtm, approved

#107 Generate job on OCP 4.15 only for serverless-operator
  pkg/prowgen/prowgen_config.go
Labels: lgtm, approved

#108 Make sure candidate OCP release is properly marked as onDemand
  pkg/prowgen/prowgen.go
Labels: lgtm, approved

#111 Chmod generate-internal-groups.sh in source image
  cmd/generate/SourceImageDockerfile.template
  pkg/project/testoutput/openshift/ci-operator/source-image/Dockerfile
Labels: lgtm, approved, ¯\_(ツ)_/¯

#112 Checkout code before setup go to use go.mod for Go version
  .github/workflows/go-unit-tests.yaml
  .github/workflows/multiarch-build.yaml
  .github/workflows/release-generate-ci.yaml
  .github/workflows/run-command-repository.yaml
  go.mod
  pkg/project/testoutput/openshift/ci-operator/build-image/Dockerfile
  pkg/project/testoutput/openshift/ci-operator/knative-images/generate/Dockerfile
  pkg/project/testoutput/openshift/ci-operator/knative-images/prowcopy/Dockerfile
  pkg/project/testoutput/openshift/ci-operator/knative-images/prowgen/Dockerfile
  pkg/project/testoutput/openshift/ci-operator/knative-images/sobranch/Dockerfile
  pkg/project/testoutput/openshift/ci-operator/knative-test-images/testselect/Dockerfile
Labels: lgtm, approved

#110 Add eventing configs for 1.13 branches
  config/eventing-istio.yaml
  config/eventing-kafka-broker.yaml
  config/eventing.yaml
Labels: approved

#114 Disable internal encryption for release-next
  config/serving.yaml
Labels: lgtm, approved
